// Package types provides ...
package types

// AttestationConveyancePreference WebAuthn Relying Parties may use AttestationConveyancePreference to
// specify their preference regarding attestation conveyance during credential generation.
// https://www.w3.org/TR/webauthn/#enum-attestation-convey
type AttestationConveyancePreference string

const (
	// PreferenceNone - This value indicates that the Relying Party is not interested in authenticator
	// attestation.
	PreferenceNone AttestationConveyancePreference = "none" // This is the default
	// PreferenceIndirect - This value indicates that the Relying Party prefers an attestation conveyance
	// yielding verifiable attestation statements, but allows the client to decide how to obtain such
	// attestation statements.
	PreferenceIndirect AttestationConveyancePreference = "indirect"
	// PreferenceDirect - This value indicates that the Relying Party wants to receive the attestation
	// statement as generated by the authenticator.
	PreferenceDirect AttestationConveyancePreference = "direct"
	// PreferenceEnterprise - This value indicates that the Relying Party wants to receive an attestation
	// statement that may include uniquely identifying information.
	PreferenceEnterprise AttestationConveyancePreference = "enterprise"
)

// IsValidAttestationCP is valid attestation conveyance preference
func IsValidAttestationCP(cp AttestationConveyancePreference) bool {
	return cp == PreferenceNone ||
		cp == PreferenceIndirect ||
		cp == PreferenceDirect ||
		cp == PreferenceEnterprise
}
